### ISSUE TITLE
AzureML Integration add-on tool error. 

### ISSUE THREAD

**Issue by cambriausa03** [seeq12/seeq-azureml#18]
MissingSectionHeaderError: File contains no section headers.
file: PosixPath('/home/datalab/.seeq/aml_config.ini'), line: 1
'{\n'

Error found at line 2 in cell 2.

**Comment by cambriausa03** [comment]
MissingSectionHeaderError                 Traceback (most recent call last)
/tmp/ipykernel_435/1909444738.py in <module>
      1 C = azureml.MlOperate(sdl_notebook_url=jupyter_notebook_url)
----> 2 C.run()

~/.local/lib/python3.8/site-packages/seeq/addons/azureml/_add_on_main.py in run(self)
     93     def run(self):
     94         display(self.app)
---> 95         self.populate_available_aml_endpoints()
     96         clear_output()
     97         return self.app

~/.local/lib/python3.8/site-packages/seeq/addons/azureml/_add_on_main.py in populate_available_aml_endpoints(self)
    114 
    115         try:
--> 116             self.inputs_provider = ModelInputsProvider(config_file=self.config_file)
    117         except AzureMLException as e:
    118             self.set_spinner_message(title="Azure Exception", message=str(e), status="ERROR")

~/.local/lib/python3.8/site-packages/seeq/addons/azureml/backend/_seeq_inputs_provider.py in __init__(self, config_file)
     48     """
     49     def __init__(self, config_file=None):
---> 50         _config.validate_configuration_file(config_file)
     51         self.endpoint_svc = AmlOnlineEndpointService(tenant_id=_config.get('azure', 'TENANT_ID'),
     52                                                      app_id=_config.get('azure', 'APP_ID'),

~/.local/lib/python3.8/site-packages/seeq/addons/azureml/_config.py in validate_configuration_file(configfile)
     27         raise FileNotFoundError(f"File {configfile} could not be found.")
     28     config = configparser.ConfigParser(allow_no_value=True)
---> 29     config.read(configfile)
     30     global configuration_parser
     31     configuration_parser = config

/usr/local/lib/python3.8/configparser.py in read(self, filenames, encoding)
    695             try:
    696                 with open(filename, encoding=encoding) as fp:
--> 697                     self._read(fp, filename)
    698             except OSError:
    699                 continue

/usr/local/lib/python3.8/configparser.py in _read(self, fp, fpname)
   1080                 # no section header in the file?
   1081                 elif cursect is None:
-> 1082                     raise MissingSectionHeaderError(fpname, lineno, line)
   1083                 # an option line?
   1084                 else:

MissingSectionHeaderError: File contains no section headers.
file: PosixPath('/home/datalab/.seeq/aml_config.ini'), line: 1
'{\n'

**Comment by monstrorivas** [comment]
@cambriausa03,

The aml_config.ini file must have the header `[azure]` in line 1.  The contents of the file should look like this (values redacted in this example):


```
[azure]
SUBSCRIPTION_ID=xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
RESOURCE_GROUP=group-name
WORKSPACE_NAME=workspace-name
TENANT_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
APP_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
APP_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxx
```
