### ISSUE TITLE
developer-notebook cannot see ACI endpoint

### ISSUE THREAD

**Issue by insm-cvx** [seeq12/seeq-azureml#6]
Our company's seeq server needs to be upgraded for us to try out the seeq-azureml library in Seeq Data Lab, so until then, we're trying to test it locally. We think we've followed the install and setup instructions properly as the notebook can successfully authenticate to our AML workspace, but we cannot see our AML endpoint in the __Model Inputs__ dropdown. Here's what we've tried so far:

1. pip installed `seeq-azureml` in a fresh conda env
2. Cloned down the [seeq-azureml repo](https://github.com/seeq12/seeq-azureml)
3. Trained and registered a simple model in AML with tags taken from the repo documentation
![seeq-model](https://user-images.githubusercontent.com/95256316/143956444-db9c59f2-bd6a-474f-887c-de7c5c663220.png)
4. Deployed the model as an [AciWebService](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aci.aciwebservice?view=azure-ml-py) with a tag of `Seeq="true"` (we previously tried with `Seeq=True`)
![seeq-endpoint](https://user-images.githubusercontent.com/95256316/143957770-22b933bc-702e-49b7-8a0e-53823cec4447.png)
5. Ran the Jupyter notebook and tried to select the endpoint.
![image](https://user-images.githubusercontent.com/95256316/143957152-e6cb3ef7-2ed0-44f0-badc-68754a779e2f.png)

**Comment by monstrorivas** [comment]
Have you tried `Seeq : true` for the tag in your Step 4? That is, the Name of the tag is `Seeq` and the Value is `true` (pay attention to the correct capitalization). Let me know if that still doesn’t work and we can troubleshoot more

**Comment by insm-cvx** [comment]
> Have you tried `Seeq : true` for the tag in your Step 4? That is, the Name of the tag is `Seeq` and the Value is `true` (pay attention to the correct capitalization). Let me know if that still doesn’t work and we can troubleshoot more

So the screenshot above shows a string of "true" and we tried a bool of True. Trying a bool of true results in an error because of the variable thing:
![bool](https://user-images.githubusercontent.com/95256316/144051761-dd4d9032-eca4-406f-b39d-9ec8819aa044.png)

**Comment by monstrorivas** [comment]
Looking at the screenshots provided, something looks different in the Tags of the endpoint as compared to the Tags of the model (where the input signals are specified). There is no `:`  in the tag of the endpoint. Can edit the tag from the Azure UI to test?

This how mine looks:
![image](https://user-images.githubusercontent.com/28580105/144100131-4bb96711-32de-4ad0-aa74-8c6ee4c9f768.png)

And if I try to edit the tag, this is what I have
![image](https://user-images.githubusercontent.com/28580105/144100763-59a76583-e9eb-4eec-b280-dc26e39211d4.png)

**Comment by monstrorivas** [comment]
@cherrera2001 
Do you have any insights on how to set the `Seeq: true` tag programmatically with `AciWebservice.deploy_configuration`? I don't see anything amiss in the steps tried above?

**Comment by cherrera2001** [comment]
Looking here [deploy_configuration](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aciwebservice?view=azure-ml-py#deploy-configuration-cpu-cores-none--memory-gb-none--tags-none--properties-none--description-none--location-none--auth-enabled-none--ssl-enabled-none--enable-app-insights-none--ssl-cert-pem-file-none--ssl-key-pem-file-none--ssl-cname-none--dns-name-label-none--primary-key-none--secondary-key-none--collect-model-data-none--cmk-vault-base-url-none--cmk-key-name-none--cmk-key-version-none--vnet-name-none--subnet-name-none-), tags are defined as a dict of type `[str,str]`, so the true should be wrapped in quotes.

**Comment by insm-cvx** [comment]
> Looking here [deploy_configuration](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.webservice.aciwebservice?view=azure-ml-py#deploy-configuration-cpu-cores-none--memory-gb-none--tags-none--properties-none--description-none--location-none--auth-enabled-none--ssl-enabled-none--enable-app-insights-none--ssl-cert-pem-file-none--ssl-key-pem-file-none--ssl-cname-none--dns-name-label-none--primary-key-none--secondary-key-none--collect-model-data-none--cmk-vault-base-url-none--cmk-key-name-none--cmk-key-version-none--vnet-name-none--subnet-name-none-), tags are defined as a dict of type `[str,str]`, so the true should be wrapped in quotes.

Yep, Seeq="true" is what we tried first (step 4 in my original post). Have you all tested the seeq-azureml functionality with ACI or AKS? I was trying with an ACI endpoint because it was quicker but we're planning to use AKS as the default moving forward.

**Comment by cherrera2001** [comment]
Our testing was primarily done with ACI as well as managed endpoints as well. I will do a bit more testing later today.

**Comment by cherrera2001** [comment]
I have identified a seemingly new bug with the AzureML REST endpoint that we use to discover endpoints. It returns endpoints with computing types of managed online compute and K8S but not ACI. I am reaching out to the MSFT team to report the issue. In the meantime, a workaround has been identified but is quite complex and would lead to increased latency in launching the add-on. I will wait to hear back on the timeline for the fix from MSFT before we implement the workaround.

**Comment by insm-cvx** [comment]
Thanks for the update! We'll try it with AKS next week since that's our preferred option anyway.

**Comment by cherrera2001** [comment]
I was able to identify a relatively performant workaround and raised a PR.
